from .recursos import Usuarios as UsuariosResource
from .recursos import Usuario as UsuarioResource
from .recursos import Productos as ProductosResource
from .recursos import Producto as ProductoResource
from .recursos import Pedidos as PedidosResource
from .recursos import Pedido as PedidoResource
from .recursos import Login as LoginResource
from .recursos import Logout as LogoutResource
from .recursos import Notificacion as NotificacionResource
from .recursos import Valoracion as ValoracionResource
