from .usuario import Usuarios as UsuariosResource
from .usuario import Usuario as UsuarioResource
from .producto import Productos as ProductosResource
from .producto import Producto as ProductoResource
from .pedido import Pedidos as PedidosResource
from .pedido import Pedido as PedidoResource
from .notificacion import Notificaciones as NotificacionesResource
from .notificacion import Notificacion as NotificacionResource
from .valoracion import Valoraciones as ValoracionesResource
from .valoracion import Valoracion as ValoracionResource
from .categorias import Categorias as CategoriasResource
from .categorias import Categoria as CategoriaResource
from .vinculacion import Vinculacion as vinculacionResource